In [2]:
pip install yfinance

Requirement already satisfied: yfinance in C:\Python312\Lib\site-packages (1.7.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in C:\Python312\Lib\site-packages (from yfinance) (4.13.3)
Requirement already satisfied: curl_cffi>=0.15 in C:\Python312\Lib\site-packages (from yfinance) (0.16.3)
Requirement already satisfied: lxml>=4.9.0 in C:\Python312\Lib\site-packages (from yfinance) (6.1.3)
Requirement already satisfied: multitasking>=0.0.7 in C:\Python312\Lib\site-packages (from yfinance) (0.0.13)
Requirement already satisfied: numpy>=1.16.5 in C:\Python312\Lib\site-packages (from yfinance) (1.26.4)
Requirement already satisfied: pandas>=1.3.0 in C:\Python312\Lib\site-packages (from yfinance) (2.2.3)
Requirement already satisfied: peewee>=3.16.2 in C:\Python312\Lib\site-packages (from yfinance) (4.5.2)
Requirement already satisfied: platformdirs>=2.0.0 in C:\Python312\Lib\site-packages (from yfinance) (4.3.7)
Requirement already satisfied: protobuf>=3.19.0 in C:\Python312\Lib\site-packages (from yfinance) (4.25.6)
Requirement already satisfied: pytz>=2022.5 in C:\Python312\Lib\site-packages (from yfinance) (2025.2)
Requirement already satisfied: requests>=2.31 in C:\Python312\Lib\site-packages (from yfinance) (2.32.3)
Requirement already satisfied: websockets>=13.0 in C:\Python312\Lib\site-packages (from yfinance) (17.1)
Requirement already satisfied: soupsieve>1.2 in C:\Python312\Lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in C:\Python312\Lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.12.2)
Requirement already satisfied: cffi>=2.0.0 in C:\Python312\Lib\site-packages (from curl_cffi>=0.15->yfinance) (2.1.1)
Requirement already satisfied: certifi>=2024.2.2 in C:\Python312\Lib\site-packages (from curl_cffi>=0.15->yfinance) (2025.1.31)
Requirement already satisfied: pycparser in C:\Python312\Lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (2.22)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Python312\Lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in C:\Python312\Lib\site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Python312\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in C:\Python312\Lib\site-packages (from requests>=2.31->yfinance) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in C:\Python312\Lib\site-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Python312\Lib\site-packages (from requests>=2.31->yfinance) (2.3.0)
Note: you may need to restart the kernel to use updated packages.

In [13]:
import yfinance as yf

adani = yf.Ticker("ADANIENT.NS")

data = adani.history(
    period="5y",
    interval="1d",
    auto_adjust=False
)

print(data)

                                  Open         High          Low        Close  \
Date
2021-10-04 00:00:00+05:30  1471.000000  1531.000000  1460.099976  1526.650024
2021-10-05 00:00:00+05:30  1515.000000  1557.849976  1512.349976  1527.650024
2021-10-06 00:00:00+05:30  1529.800049  1541.000000  1472.000000  1479.550049
2021-10-07 00:00:00+05:30  1502.849976  1535.750000  1490.000000  1520.750000
2021-10-08 00:00:00+05:30  1522.000000  1569.449951  1511.449951  1547.900024
...                                ...          ...          ...          ...
2026-09-25 00:00:00+05:30  2920.000000  2939.899902  2902.500000  2916.500000
2026-09-28 00:00:00+05:30  2924.000000  2924.000000  2811.000000  2831.100098
2026-09-29 00:00:00+05:30  2834.600098  2972.899902  2793.699951  2972.899902
2026-09-30 00:00:00+05:30  2910.000000  2957.600098  2880.000000  2903.399902
2026-10-01 00:00:00+05:30  2900.000000  2903.699951  2772.000000  2816.800049

                             Adj Close   Volume  Dividends  Stock Splits
Date
2021-10-04 00:00:00+05:30  1523.249634  3209302        0.0           0.0
2021-10-05 00:00:00+05:30  1524.247314  2544835        0.0           0.0
2021-10-06 00:00:00+05:30  1476.254517  1777998        0.0           0.0
2021-10-07 00:00:00+05:30  1517.362793  1919106        0.0           0.0
2021-10-08 00:00:00+05:30  1544.452271  2646112        0.0           0.0
...                                ...      ...        ...           ...
2026-09-25 00:00:00+05:30  2916.500000   570504        0.0           0.0
2026-09-28 00:00:00+05:30  2831.100098  1259525        0.0           0.0
2026-09-29 00:00:00+05:30  2972.899902  4062231        0.0           0.0
2026-09-30 00:00:00+05:30  2903.399902  1663023        0.0           0.0
2026-10-01 00:00:00+05:30  2816.800049  2100334        0.0           0.0

[1240 rows x 8 columns]

In [18]:
pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   ---------------------------------------- 0/2 [et-xmlfile]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [14]:
path = r"C:\Users\hp\OneDrive\Desktop\Data analyst project\CASE STUDIES Data Analyst\Stock Market Analysis\Indian_Stock_List_TCS_Infosys_Reliance_Adani.xlsx"

In [15]:
import pandas as pd

In [21]:
df=pd.read_excel(path)
df["Stock Symbol"]

0            TCS.NS
1           INFY.NS
2       RELIANCE.NS
3       ADANIENT.NS
4        HCLTECH.NS
5            ITC.NS
6     BHARTIARTL.NS
7     BAJFINANCE.NS
8             LT.NS
9          TITAN.NS
10     SUNPHARMA.NS
11     KOTAKBANK.NS
12       SBILIFE.NS
13          NTPC.NS
14          ONGC.NS
15      HINDALCO.NS
16    ASIANPAINT.NS
17         DMART.NS
Name: Stock Symbol, dtype: object

In [24]:
all_stock_symbol = df["Stock Symbol"].values
all_stock_symbol

array(['TCS.NS', 'INFY.NS', 'RELIANCE.NS', 'ADANIENT.NS', 'HCLTECH.NS',
       'ITC.NS', 'BHARTIARTL.NS', 'BAJFINANCE.NS', 'LT.NS', 'TITAN.NS',
       'SUNPHARMA.NS', 'KOTAKBANK.NS', 'SBILIFE.NS', 'NTPC.NS', 'ONGC.NS',
       'HINDALCO.NS', 'ASIANPAINT.NS', 'DMART.NS'], dtype=object)

In [44]:
import pandas as pd
import yfinance as yf

all_stock_symbol = [
    'TCS.NS', 'INFY.NS', 'RELIANCE.NS', 'ADANIENT.NS', 'HCLTECH.NS',
       'ITC.NS', 'BHARTIARTL.NS', 'BAJFINANCE.NS', 'LT.NS', 'TITAN.NS',
       'SUNPHARMA.NS', 'KOTAKBANK.NS', 'SBILIFE.NS', 'NTPC.NS', 'ONGC.NS',
       'HINDALCO.NS', 'ASIANPAINT.NS', 'DMART.NS'
]

empty_df = pd.DataFrame()

for i in all_stock_symbol:

    

    stock = yf.Ticker(i)

    data = stock.history(
        period="6y",
        interval="1d",
        auto_adjust=False
    )

    # Check if data exists
    if data.empty:
        print(f"No data found for {i}")
        continue

    # Convert index to Date column
    data = data.reset_index()

    # Add stock symbol
    data["Company_name"] = i

    # Add Dividends if missing
    if "Dividends" not in data.columns:
        data["Dividends"] = 0.0

    # Add Stock Splits if missing
    if "Stock Splits" not in data.columns:
        data["Stock Splits"] = 0.0

    # Keep only required columns
    data = data[
        [
            "Date",
            "Open",
            "High",
            "Low",
            "Close",
            "Volume",
            "Dividends",
            "Stock Splits",
            "Company_name"
        ]
    ]

    # Combine all stocks
    empty_df = pd.concat(
        [empty_df, data],
        ignore_index=True
    )

# Final dataset
stock_table = empty_df.copy()

stock_table

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Company_name
0,2020-10-05 00:00:00+05:30,2620.000000,2728.100098,2603.050049,2705.800049,17412105,0.0,0.0,TCS.NS
1,2020-10-06 00:00:00+05:30,2736.000000,2736.000000,2650.100098,2714.300049,9846367,0.0,0.0,TCS.NS
2,2020-10-07 00:00:00+05:30,2742.000000,2770.000000,2703.000000,2735.949951,9656101,0.0,0.0,TCS.NS
3,2020-10-08 00:00:00+05:30,2800.000000,2885.000000,2800.000000,2825.699951,19839329,0.0,0.0,TCS.NS
4,2020-10-09 00:00:00+05:30,2810.000000,2829.850098,2780.000000,2812.949951,7739245,0.0,0.0,TCS.NS
...,...,...,...,...,...,...,...,...,...
26777,2026-09-25 00:00:00+05:30,3789.800049,3834.199951,3771.600098,3834.199951,297635,0.0,0.0,DMART.NS
26778,2026-09-28 00:00:00+05:30,3815.000000,3833.000000,3781.000000,3803.500000,361700,0.0,0.0,DMART.NS
26779,2026-09-29 00:00:00+05:30,3803.500000,3849.000000,3746.199951,3750.000000,656759,0.0,0.0,DMART.NS
26780,2026-09-30 00:00:00+05:30,3769.500000,3865.000000,3769.500000,3801.399902,620771,0.0,0.0,DMART.NS
26781,2026-10-01 00:00:00+05:30,3809.800049,3880.000000,3781.399902,3813.000000,652283,0.0,0.0,DMART.NS

In [45]:
stock_table

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Company_name
0,2020-10-05 00:00:00+05:30,2620.000000,2728.100098,2603.050049,2705.800049,17412105,0.0,0.0,TCS.NS
1,2020-10-06 00:00:00+05:30,2736.000000,2736.000000,2650.100098,2714.300049,9846367,0.0,0.0,TCS.NS
2,2020-10-07 00:00:00+05:30,2742.000000,2770.000000,2703.000000,2735.949951,9656101,0.0,0.0,TCS.NS
3,2020-10-08 00:00:00+05:30,2800.000000,2885.000000,2800.000000,2825.699951,19839329,0.0,0.0,TCS.NS
4,2020-10-09 00:00:00+05:30,2810.000000,2829.850098,2780.000000,2812.949951,7739245,0.0,0.0,TCS.NS
...,...,...,...,...,...,...,...,...,...
26777,2026-09-25 00:00:00+05:30,3789.800049,3834.199951,3771.600098,3834.199951,297635,0.0,0.0,DMART.NS
26778,2026-09-28 00:00:00+05:30,3815.000000,3833.000000,3781.000000,3803.500000,361700,0.0,0.0,DMART.NS
26779,2026-09-29 00:00:00+05:30,3803.500000,3849.000000,3746.199951,3750.000000,656759,0.0,0.0,DMART.NS
26780,2026-09-30 00:00:00+05:30,3769.500000,3865.000000,3769.500000,3801.399902,620771,0.0,0.0,DMART.NS
26781,2026-10-01 00:00:00+05:30,3809.800049,3880.000000,3781.399902,3813.000000,652283,0.0,0.0,DMART.NS